# assemble_full_ebook.py
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path
from datetime import datetime


ROOT = Path(__file__).resolve().parent  # this script's folder (currently sweep_up/inbox)


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _extract_block(html: str, tag: str) -> str | None:
    m = re.search(rf"<{tag}\b[^>]*>(.*?)</{tag}>", html, flags=re.I | re.S)
    return m.group(1).strip() if m else None


def extract_mainish(html: str) -> str:
    for tag in ("main", "article", "body"):
        blk = _extract_block(html, tag)
        if blk:
            return blk
    return html  # last resort


def strip_base_tag(html: str) -> str:
    return re.sub(r"<base\b[^>]*>\s*", "", html, flags=re.I)


def strip_mathjax_scripts(html: str) -> str:
    # remove MathJax config blocks + the CDN loader, we'll add one unified config
    html = re.sub(r"<script>\s*window\.MathJax\s*=\s*\{.*?\};\s*</script>", "", html, flags=re.I | re.S)
    html = re.sub(r"<script[^>]+mathjax@3[^>]+></script>", "", html, flags=re.I)
    return html


def copy_if_exists(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if not src.exists():
        print(f"[WARN] Missing (not copied): {src}")
        return
    shutil.copy2(src, dst)
    print(f"[OK] Copied: {src.name} -> {dst}")


def run_annual_exhibits(outdir: Path) -> None:
    """
    Generate annual exhibits directly into the print bundle figures/ directory.
    """
    outdir.mkdir(parents=True, exist_ok=True)

    # Adjust this to your actual canonical location over time.
    # For now, keep your existing CSV name in inbox by default.
    default_csv = ROOT / "Homeatix housing market model(Sheet1) (4).csv"
    if not default_csv.exists():
        print(f"[WARN] Annual CSV not found at: {default_csv}")
        print("       Annual exhibits will not be regenerated unless you fix the CSV path.")
        return

    script = ROOT / "homeatix_annual_exhibits.py"
    if not script.exists():
        raise FileNotFoundError(f"Missing exhibit generator script: {script}")

    cmd = [
        sys.executable,
        str(script),
        "--csv",
        str(default_csv),
        "--outdir",
        str(outdir),
    ]
    print("[RUN] " + " ".join(cmd))
    subprocess.check_call(cmd)


def bundle_extra_figures(inbox: Path, figures_dir: Path) -> None:
    """
    Copy any extra figures generated by other scripts (if present).
    """
    # Your uploaded quarterly cash-share chart (England vs Wales)
    copy_if_exists(inbox / "england_wales_cash_share_quarterly.png", figures_dir / "england_wales_cash_share_quarterly.png")

    # If you later standardise the cashshare diagnostic name differently, add it here.


def part1_html() -> str:
    """
    Part I block injected before both papers.
    Figure paths are relative to index.html (figures/..).
    """
    return """
<section id="part1">
  <h2>Part I — The 2024 Foundations: Market Function Before Price</h2>

  <p>
    Home@ix began from an observation that sounds simple but changes the whole measurement problem:
    in UK housing stress regimes, the market does not reliably clear through orderly repricing.
    It often clears through <strong>rationing participation</strong>. Turnover collapses, transaction chains fail,
    mortgage-dependent households are screened out, and the observed price index becomes a <em>selected statistic</em> produced by a thinner, wealthier transacting set.
  </p>

  <p>
    Part I sets the domain terms for the rest of the book. Before we define FAIR (the derived, reproducible regime indicator),
    we anchor the foundational claim with a canonical diagnostic module: turnover (market liquidity), cash-versus-mortgage dynamics (access to finance),
    and the balance between new build and old stock activity (delivery and churn capacity).
  </p>

  <div class="box">
    <strong>Working proposition:</strong> affordability is not only a burden ratio; it is an <strong>access-and-allocation regime outcome</strong>.
    In thin markets, price signals can lag while exclusion and mobility failure worsen in real time.
  </div>

  <hr />

  <section id="part1-exhibits">
    <h3>1. A canonical diagnostic module (market depth, access, and mix)</h3>
    <p>
      The exhibits below are treated as a single system lens. Read together, they diagnose whether the housing system is clearing via price,
      or via <em>quantity and composition</em> (thin-market clearing).
    </p>

    <hr />

    <section id="part1-fig1">
      <h3>Figure 1 — Turnover and cash share (annual)</h3>
      <p>
        Turnover is the housing market’s <strong>functionality / liquidity</strong> indicator: how many homes change hands relative to the stock.
        Cash share is a <strong>participation / exclusion</strong> indicator: when cash share rises alongside weak turnover, it is consistent with
        mortgage-dependent households being rationed out by rates, underwriting, or deposit constraints.
      </p>
      <figure>
        <img src="figures/exhibit_1_turnover_cashshare_annual.png"
             alt="Exhibit 1 — Stock turnover (%) and cash share (annual)" loading="lazy" />
        <figcaption><strong>Figure 1.</strong> Stock turnover and cash share (annual).</figcaption>
      </figure>
    </section>

    <hr />

    <section id="part1-fig2a">
      <h3>Figure 2a — Transaction levels: old stock vs new build (annual)</h3>
      <p>
        “Housing activity” is not one market. Old stock dominates volume and is more <strong>credit- and chain-sensitive</strong>.
        New build volumes reflect additional constraints (planning, labour, build finance, developer pacing). The split helps distinguish
        <em>access/finance stress</em> from <em>delivery/capacity stress</em>.
      </p>
      <figure>
        <img src="figures/exhibit_2a_transaction_levels_annual.png"
             alt="Exhibit 2a — Transaction levels: old stock vs new build (annual)" loading="lazy" />
        <figcaption><strong>Figure 2a.</strong> Transaction levels: old stock vs new build (annual).</figcaption>
      </figure>
    </section>

    <hr />

    <section id="part1-fig2b">
      <h3>Figure 2b — Transaction mix shares (annual)</h3>
      <p>
        Mix shares reveal <strong>compositional clearing</strong>: who is still able to transact when the market thins.
        Shifts in shares can signal allocation stress even when headline prices appear stable.
      </p>
      <figure>
        <img src="figures/exhibit_2b_transaction_mix_shares_annual.png"
             alt="Exhibit 2b — Transaction mix shares (annual)" loading="lazy" />
        <figcaption><strong>Figure 2b.</strong> Transaction mix shares (annual).</figcaption>
      </figure>
    </section>

    <hr />

    <section id="part1-fig4">
      <h3>Figure 4 — Indexed price vs indexed turnover (annual)</h3>
      <p>
        When turnover collapses, price indices can lag or understate stress because fewer transactions generate weaker price discovery.
        Liquidity risk becomes macro-relevant.
      </p>
      <figure>
        <img src="figures/exhibit_4_price_vs_turnover_index_annual.png"
             alt="Exhibit 4 — House price vs turnover (indexed, annual)" loading="lazy" />
        <figcaption><strong>Figure 4.</strong> Indexed price vs indexed turnover (annual).</figcaption>
      </figure>
    </section>

    <hr />

    <section id="part1-cashshare-ew">
      <h3>Supplement — Cash purchases share (England vs Wales, quarterly)</h3>
      <p>
        A cross-nation comparison helps separate broad regime shifts from local noise.
        Divergences can reflect geography-specific credit conditions, investor mix, or compositional effects.
      </p>
      <figure>
        <img src="figures/england_wales_cash_share_quarterly.png"
             alt="Cash purchases as a proportion of total transactions (quarterly): England vs Wales"
             loading="lazy" />
        <figcaption><strong>Supplement.</strong> Cash purchases as a proportion of total transactions (quarterly): England vs Wales.</figcaption>
      </figure>
    </section>
  </section>

  <hr />

  <section id="part1-bridge-to-identity">
    <h3>2. Why this forces an accounting identity (and later, FAIR)</h3>
    <p>
      If the system clears through <strong>quantities and composition</strong> under stress, then an affordability framework must track access-to-finance
      and market depth/throughput — not just price levels.
    </p>
    <div class="box">
      <strong>Bridge statement:</strong> Part I defines the failure mode (thin-market clearing). FAIR later converts that diagnosis into a reproducible quarterly monitor.
    </div>
  </section>

  <hr />

  <section id="part1-source-note">
    <h3>3. Source note (reproducibility)</h3>
    <ul>
      <li><strong>Exhibits generator:</strong> <code>sweep_up/inbox/homeatix_annual_exhibits.py</code></li>
      <li><strong>Bundled figures:</strong> <code>figures/</code> (relative to this <code>index.html</code>)</li>
    </ul>
  </section>
</section>
""".strip()


def main():
    follow = ROOT / "homeix_followup_paper.html"
    fair = ROOT / "homeix_fair_paper.html"

    if not follow.exists():
        raise FileNotFoundError(f"Missing {follow}")
    if not fair.exists():
        raise FileNotFoundError(f"Missing {fair}")

    outdir = Path.cwd()  # run with CWD = publication/print_$stamp
    outdir.mkdir(parents=True, exist_ok=True)

    figures_dir = outdir / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)

    # 1) Regenerate exhibits into the bundle
    run_annual_exhibits(figures_dir)

    # 2) Copy any additional figures that live in inbox
    bundle_extra_figures(ROOT, figures_dir)

    # 3) Assemble HTML
    follow_html = strip_mathjax_scripts(strip_base_tag(_read(follow)))
    fair_html = strip_mathjax_scripts(strip_base_tag(_read(fair)))

    follow_body = extract_mainish(follow_html)
    fair_body = extract_mainish(fair_html)

    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    known_issues = """
<section class="box">
  <h2>Known issues (pre-publication)</h2>
  <ul>
    <li><strong>Animation rendering:</strong> some animated assets may not display in all viewers. Use exported GIF/PNG fallbacks in <code>assets/</code> where provided.</li>
    <li><strong>Math rendering:</strong> equations are standardised to <code>$$...$$</code>. If any equations appear unrendered, open the HTML in a modern browser (MathJax-enabled).</li>
  </ul>
</section>
""".strip()

    out = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Home@ix — Full Working Book (print bundle)</title>

  <!-- MathJax (standardised to $$..$$) -->
  <script>
    window.MathJax = {{
      tex: {{
        displayMath: [['$$','$$']],
        inlineMath: []
      }}
    }};
  </script>
  <script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>

  <style>
    :root {{ --max: 980px; }}
    body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; line-height: 1.6; margin: 2rem; color: #111; }}
    main {{ max-width: var(--max); margin: 0 auto; }}
    h1, h2, h3 {{ line-height: 1.15; }}
    .meta {{ color: #444; }}
    .box {{ border: 1px solid #ddd; padding: 12px 14px; border-radius: 10px; background: #fafafa; margin: 1.2rem 0; }}
    figure {{ margin: 1.25rem 0; padding: .75rem; border: 1px dashed #cfcfcf; border-radius: 10px; }}
    figcaption {{ color: #444; font-size: .95rem; }}
    hr {{ border: 0; border-top: 1px solid #eee; margin: 2rem 0; }}

    figure {{ max-width: 900px; margin-left: auto; margin-right: auto; }}
    figure img {{ display: block; max-width: 100%; height: auto; margin: 0 auto; }}
  </style>
</head>
<body>
  <main>
    <header>
      <h1>Home@ix — Full Working Book (Draft)</h1>
      <p class="meta"><strong>Print bundle:</strong> {outdir.name} &nbsp;|&nbsp; <strong>Built:</strong> {stamp}</p>
    </header>

    {known_issues}

    <hr />

    {part1_html()}

    <hr />

    <section id="followup">
      <h2>Follow-up Paper</h2>
      {follow_body}
    </section>

    <hr />

    <section id="fair">
      <h2>FAIR Paper</h2>
      {fair_body}
    </section>

    <hr />
  </main>
</body>
</html>
"""

    (outdir / "index.html").write_text(out, encoding="utf-8")
    print(f"Wrote: {outdir / 'index.html'}")


if __name__ == "__main__":
    main()
